/*First step - Obtaing the data and interperting it*/

/*I ran this query to see what data I can work with*/ 
SELECT TOP (1000) [game_id]
      ,[date]
      ,[player]
      ,[rank]
      ,[substitute_player]
      ,[winner]
      ,[score]
      ,[color]
      ,[num_of_cities]
      ,[num_of_settlement]
      ,[num_of_roads]
      ,[num_of_dev_cards]
      ,[buy_dev_card_first]
      ,[builds_city_first]
      ,[builds_settlement_first]
      ,[num_of_harbor]
      ,[which_resources_first]
      ,[cashier]
      ,[time_in_min]
      ,[is_extension]
      ,[start_time]
      ,[longest_road]
      ,[largest_army]
      ,[first_brick_harbor]
      ,[first_ore_harbor]
      ,[first_grain_harbor]
      ,[first_wool_harbor]
      ,[first_lumber_harbor]
      ,[first_3to1_harbor]
      ,[num_of_brick_harbor]
      ,[num_of_grain_harbor]
      ,[num_of_3to1_harbor]
      ,[num_of_lumber_harbor]
      ,[num_of_ore_harbor]
      ,[num_of_wool_harbor]
      ,[initial_dices]
      ,[dessert_placement]
  FROM [catan].[dbo].[catan_scores]
